"""empty message

Revision ID: 29c87a57dcf2
Revises: 2b5655e83d41
Create Date: 2025-03-23 19:05:01.022764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c87a57dcf2'
down_revision = '2b5655e83d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allotment_captial', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_column('allotment_captial')

    # ### end Alembic commands ###
