"""empty message

Revision ID: 609814288c65
Revises: 30b4d3eb5095
Create Date: 2025-03-25 12:29:56.387976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609814288c65'
down_revision = '30b4d3eb5095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
