"""empty message

Revision ID: 73e0f3debbf9
Revises: 3afd4da6fb36
Create Date: 2025-03-20 14:54:24.641678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73e0f3debbf9'
down_revision = '3afd4da6fb36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cycle_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_column('cycle_count')

    # ### end Alembic commands ###
