"""empty message

Revision ID: 990458e15574
Revises: 01289fe66502
Create Date: 2025-03-20 12:20:31.689984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990458e15574'
down_revision = '01289fe66502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_column('total_quantity')

    # ### end Alembic commands ###
