"""empty message

Revision ID: a533561919fd
Revises: 40e99ddc0100
Create Date: 2025-03-22 17:20:23.082649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a533561919fd'
down_revision = '40e99ddc0100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('available_balance')
        batch_op.drop_column('used_balance')
        batch_op.drop_column('remaining_balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remaining_balance', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('used_balance', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('available_balance', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
