"""empty message

Revision ID: d911e05dae38
Revises: a533561919fd
Create Date: 2025-03-22 17:22:17.451066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd911e05dae38'
down_revision = 'a533561919fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_balance', sa.Float(), server_default='0.0', nullable=False))
        batch_op.add_column(sa.Column('remaining_balance', sa.Float(), server_default='0.0', nullable=False))
        batch_op.add_column(sa.Column('used_balance', sa.Float(), server_default='0.0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('used_balance')
        batch_op.drop_column('remaining_balance')
        batch_op.drop_column('available_balance')

    # ### end Alembic commands ###
