"""empty message

Revision ID: f0e1de2717d8
Revises: 609814288c65
Create Date: 2025-03-31 12:58:00.025420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e1de2717d8'
down_revision = '609814288c65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_status', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['unique_order_id'])
        batch_op.create_unique_constraint(None, ['order_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_status', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
